# Generated by Django 3.1.2 on 2020-10-22 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombres o Razon social')),
                ('address', models.CharField(max_length=150, verbose_name='Direccion')),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='Ruc')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('fecha_created', models.DateTimeField(auto_now=True)),
                ('fecha_updated', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombres o Razon social')),
                ('desc', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('fecha_created', models.DateTimeField(auto_now=True)),
                ('fecha_updated', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(default=datetime.datetime.now)),
                ('fecha_venc', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('cantidad', models.IntegerField(default=0)),
                ('pre', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.client')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.product')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['id'],
            },
        ),
    ]
